### ISSUE TITLE
Wrong audience for dataset-catalogue & api-catalogue

### ISSUE THREAD

**Issue by NilsOveTen** [Informasjonsforvaltning/auth-utils-java#3]
registration-api => fdk-registration-api

**Comment by KjerstiSteien** [comment]
@NilsOveTen husker du hva denne saken gjelder? Og er den fortsatt relevant?

**Comment by NilsOveTen** [comment]
@KjerstiSteien repoet ble lagd i 2019 for å ha en enkel mock av keycloak/sso, for å bruke det når vi kjørte opp api lokalt. Men ila 2020 gikk vi over til å konsekvent bruke staging når vi kjørte ting opp lokalt, vi kan fint lukke issuet og arkivere hele repoet.
